#!/usr/bin/env python

import os
import re
from urllib2 import urlopen

url = 'http://wiki.lesswrong.com/mediawiki/skins/lesswrong/main.css'
selector_prefix = '#wiki-content '
header_comment = '/* This file was auto-generated by scripts/generate_wiki_css.py */\n'

here = os.path.dirname(os.path.dirname(__file__))
out_filename = os.path.join(here, 'r2', 'r2', 'public', 'static', 'wiki.css')


def main():
    css = urlopen(url).read()

    # This "parsing" code is terrible, and only works on CSS1, but for now, it'll do.
    css = re.sub(r'(?s)\/\*.*?\*\/', '', css)
    css = selector_prefix + re.sub(r'(?<=\})\s*', selector_prefix, css) + '{}'

    with open(out_filename, 'w') as file:
        file.write(header_comment)
        file.write(css)
    print('CSS written to {0}'.format(out_filename))


main()
